const {app,BrowserWindow}=require('electron');const fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=path.join(root,'artifacts');
const server=require('http').createServer((req,res)=>{const file=path.resolve(root,'docs','.'+new URL(req.url,'http://localhost').pathname.replace(/\/$/,'/index.html'));if(!file.startsWith(path.join(root,'docs')+path.sep)){res.writeHead(403);return res.end();}fs.readFile(file,(error,data)=>{const securityHeaders=Object.fromEntries(fs.readFileSync(path.join(root,'docs/_headers'),'utf8').split('\n').filter(line=>/^  [A-Za-z-]+:/.test(line)).map(line=>{const colon=line.indexOf(':');return [line.slice(0,colon).trim(),line.slice(colon+1).trim()];}));res.writeHead(error?404:200,{...securityHeaders,'Content-Type':file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':file.endsWith('.html')?'text/html':file.endsWith('.svg')?'image/svg+xml':'application/octet-stream'});res.end(error?'Not found':data);});});
app.on('before-quit',()=>server.close());
app.setPath('userData',path.join(out,'site-test-profile'));
const motion=process.argv.includes('--motion');
if(!motion)app.commandLine.appendSwitch('force-prefers-reduced-motion','reduce');
app.whenReady().then(async()=>{
  const win=new BrowserWindow({width:1440,height:1050,show:false,frame:false,webPreferences:{offscreen:true}});const errors=[];
  win.webContents.on('console-message',(_e,level,message)=>{if(level===3&&!/Content Security/.test(message))errors.push(message);});
  await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
  await win.loadURL('http://127.0.0.1:'+server.address().port);
  await new Promise(resolve=>setTimeout(resolve,1200));
  assert.equal(await win.webContents.executeJavaScript("document.querySelector('#particle-scene canvas').dataset.particleForm"),'helix');
  assert.equal(await win.webContents.executeJavaScript("document.querySelector('#motion-toggle').hidden"),false);
  assert.equal(await win.webContents.executeJavaScript("document.querySelector('.hero-strings')"),null);
  assert.equal(await win.webContents.executeJavaScript("!!document.querySelector('.shape-wordmark')"),false);
  fs.writeFileSync(path.join(out,'aetherai-site-spiral-hero.png'),(await win.webContents.capturePage()).toPNG());
  if(motion){
    await new Promise(resolve=>setTimeout(resolve,1600));
    const before=await win.webContents.executeJavaScript("document.querySelector('#particle-scene canvas').toDataURL()");
    await new Promise(resolve=>setTimeout(resolve,180));
    assert.ok(before!==await win.webContents.executeJavaScript("document.querySelector('#particle-scene canvas').toDataURL()"),'Helix must visibly animate');
    await win.webContents.executeJavaScript("document.querySelector('#motion-toggle').click()");
    await new Promise(resolve=>setTimeout(resolve,100));
    const paused=await win.webContents.executeJavaScript("document.querySelector('#particle-scene canvas').toDataURL()");
    await new Promise(resolve=>setTimeout(resolve,150));
    assert.ok(paused===await win.webContents.executeJavaScript("document.querySelector('#particle-scene canvas').toDataURL()"),'Pause freezes particles');
    await win.webContents.executeJavaScript("document.querySelector('#motion-toggle').click();scrollTo({top:innerHeight,behavior:'instant'})");
    await new Promise(resolve=>setTimeout(resolve,900));
    assert.equal(await win.webContents.executeJavaScript("document.querySelector('#particle-scene canvas').dataset.particleForm"),'mark');
    assert.ok(await win.webContents.executeJavaScript("Number(document.querySelector('.landing-sculpture').dataset.scrollProgress)>.6"));
    assert.ok(await win.webContents.executeJavaScript("document.querySelector('#possibilities').classList.contains('in')"),'Scrolling reveals information');
    await win.webContents.executeJavaScript("const card=document.querySelector('.button');const r=card.getBoundingClientRect();card.dispatchEvent(new PointerEvent('pointermove',{clientX:r.right-2,clientY:r.top+r.height/2,pointerType:'mouse'}));");
    assert.ok(await win.webContents.executeJavaScript("Number(document.querySelector('.button').style.getPropertyValue('--edge-proximity'))>90"));
    fs.writeFileSync(path.join(out,'aetherai-site-motion.png'),(await win.webContents.capturePage()).toPNG());
  }
  assert.equal(await win.webContents.executeJavaScript('document.documentElement.scrollWidth <= innerWidth'),true);
  assert.ok(await win.webContents.executeJavaScript("[...document.images].filter(image=>image.getBoundingClientRect().top<innerHeight).every(image=>image.complete&&image.naturalWidth>0)"));
  await win.webContents.executeJavaScript("document.querySelector('#tab-cloud').click()");
  assert.equal(await win.webContents.executeJavaScript("document.querySelector('#tab-cloud').getAttribute('aria-selected')"),'true');
  assert.match(await win.webContents.executeJavaScript("document.querySelector('#demo-content').textContent"),/API/);
  fs.writeFileSync(path.join(out,'aetherai-site-desktop.png'),(await win.webContents.capturePage()).toPNG());
  const height=await win.webContents.executeJavaScript('document.documentElement.scrollHeight');
  win.webContents.debugger.attach('1.3');
  const full=await win.webContents.debugger.sendCommand('Page.captureScreenshot',{captureBeyondViewport:true,clip:{x:0,y:0,width:1440,height,scale:1}});
  fs.writeFileSync(path.join(out,'aetherai-site-full.png'),Buffer.from(full.data,'base64'));
  win.setSize(390,844);await new Promise(resolve=>setTimeout(resolve,250));
  await win.webContents.executeJavaScript("scrollTo({top:0,behavior:'instant'})");
  assert.equal(await win.webContents.executeJavaScript('document.documentElement.scrollWidth <= innerWidth'),true);
  fs.writeFileSync(path.join(out,'aetherai-site-mobile.png'),(await win.webContents.capturePage()).toPNG());
  for(const code of ['en','ru','es','pt','fr','de','it','tr','pl','uk']){
    await win.webContents.executeJavaScript(`document.querySelector('#language-toggle').click();document.querySelector('[data-language="${code}"]').click()`);
    assert.equal(await win.webContents.executeJavaScript('document.documentElement.lang'),code);
    assert.equal(await win.webContents.executeJavaScript('document.documentElement.scrollWidth <= innerWidth'),true,code+' mobile overflow');
    await win.webContents.executeJavaScript("document.querySelector('#tab-cloud').click()");
    assert.match(await win.webContents.executeJavaScript("document.querySelector('#demo-content').textContent"),/API/);
    assert.equal(await win.webContents.executeJavaScript("document.querySelectorAll('.download-grid a').length"),6);
  }
  await win.webContents.reload();await new Promise(resolve=>setTimeout(resolve,1200));
  assert.equal(await win.webContents.executeJavaScript('document.documentElement.lang'),'uk');
  await win.webContents.executeJavaScript("document.querySelector('#language-toggle').click();document.querySelector('[data-language=en]').click();document.querySelector('#language-toggle').click();");
  await new Promise(resolve=>setTimeout(resolve,250));
  await win.webContents.executeJavaScript("document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'End',bubbles:true}))");
  assert.equal(await win.webContents.executeJavaScript('document.activeElement.dataset.language'),'uk',JSON.stringify(await win.webContents.executeJavaScript("({active:document.activeElement.outerHTML.slice(0,250),open:document.getElementById('language-toggle').getAttribute('aria-expanded'),inert:document.getElementById('language-options').inert,visibility:getComputedStyle(document.getElementById('language-options')).visibility})")));
  await win.webContents.executeJavaScript("document.activeElement.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}))");
  assert.equal(await win.webContents.executeJavaScript("document.querySelector('#language-toggle').getAttribute('aria-expanded')"),'false');
  win.setSize(1440,1050);
  await win.webContents.executeJavaScript("document.querySelectorAll('.reveal').forEach(el=>el.classList.add('in'));document.querySelector('#download').scrollIntoView({behavior:'instant'})");
  await new Promise(resolve=>setTimeout(resolve,300));
  fs.writeFileSync(path.join(out,'aetherai-site-downloads.png'),(await win.webContents.capturePage()).toPNG());
  assert.ok(await win.webContents.executeJavaScript("[...document.querySelectorAll('a[href^=\"#\"]')].every(a=>a.hash===''||document.getElementById(a.hash.slice(1)))"));
  assert.deepEqual(errors,[]);console.log('PASS: desktop/mobile, 10 languages, persistence, keyboard menu, feature tabs, six downloads, no console errors');win.destroy();app.quit();
}).catch(error=>{console.error(error.message);app.exit(1);});
